---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    
  # environment: # Web server environment variables 
  #   ENVIRONMENT: production
  #   TYPEORM_CONNECTION: '{{ TYPEORM_CONNECTION }}'
  #   TYPEORM_ENTITIES: '{{TYPEORM_ENTITIES}}'
  #   TYPEORM_HOST: '{{TYPEORM_HOST}}'
  #   TYPEORM_PORT: '{{TYPEORM_PORT}}'
  #   TYPEORM_USERNAME: '{{TYPEORM_USERNAME}}'
  #   TYPEORM_PASSWORD: '{{TYPEORM_PASSWORD}}'
  #   TYPEORM_DATABASE: '{{TYPEORM_DATABAS}}'

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection: # 600 sec delay triggers timout without output Error
        timeout: 600
    - name: "install python for Ansible."
      # Your code here
      become: yes
      become_method: sudo 
      apt: 
        name: "python3"
        update_cache: yes

  roles:
    # Your code here
    - configure-server
