---
- name: "Install Node and pm2"
  become: yes
  become_method: sudo
  shell: |
    apt install -y nodejs npm
    npm install -g pm2@latest

- name: "Copy package file"
  become: yes
  copy: 
    src: package.json
    dist: /home/ubuntu

- name: "Install modules and fix"
  become: yes 
  shell:
    npm install
    npm audit fix --audit-level=critical --force
  register: installation

- name: "Print installations results"
  debug:
    msg: "{{ installation.stderr_lines }}"
    