---
- name: Copy build artifacts
  copy:
    src:  artifacts.tar.gzip
    dest: /home/ubuntu
  
- name: "Extract build artifacts"
  become: yes
  become_method: sudo 
  shell: |
    # extract 
    tar -xf artifacts.tar.gzip
    
    # remove required *.gzip file
    rm -f artifacts.tar.gzip
  register: extraction

- name: "Run backend server"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 start dist/main.js
    pm2 log 0 -lines 50 --json --nostream
  register: launch

- name: Print extraction results
  debug:
    msg: "{{ extraction.stdout_lines }}"

- name: Print launch results
  debug:
    msg: "{{ launch.stdout_lines }}"
