---
- name: Copy build artifacts
  copy:
    src:  artifacts.tar.gzip
    dest: /home/ubuntu
  
- name: "Extract build artifacts"
  become: yes
  shell: |
    # extract 
    tar -xf artifacts.tar.gzip

    # remove required *.gzip file
    rm -f artifacts.tar.gzip

- name: "Run backend server"
  become: yes
  shell: |
    cd /home/ubuntu/
    pm2 start dist/main.js
  register: launch

- name: "Check pm2 logs"
  become: yes
  shell: |
    cat /root/.pm2/logs/main-out.log
  register: logs

- name: Print launch results
  debug:
    msg: "{{ launch.stdout_lines }}"

- name: Print logs
  debug:
    msg: "{{ logs.stdout_lines }}"


