---
- name: "Make web home dir"
  become: yes
  become_method: sudo 
  shell:
    mkdir /var/www/

- name: Copy build artifacts
  copy:
    src: /home/circleci/project/backend"
    dest: /root/home/
  
# - name: "Extract build artifacts"
#   become: yes
#   become_method: sudo 
#   shell: |
#     cd /var/www/
#     # extract 
#     tar -xf artifacts.tar.gzip
#   register: extration

- name: "Run backend server"
  become: yes 
  become_method: sudo 
  shell: |
    cd /var/www/
    pm2 start dist/main.js
    pm2 log 0 --nostream
  register: launch

- name: Print extraction results
  debug:
    msg: "{{ extraction.stdout_lines }}"

- name: Print launch results
  debug:
    msg: "{{ launch.stdout_lines }}"
