---
- name: Copy build artifacts
  copy:
    src:  artifacts.tar.gzip
    dest: /home/ubuntu
  
- name: "Extract build artifacts"
  become: yes
  shell: |
    # extract 
    tar -xf artifacts.tar.gzip
    
    # remove required *.gzip file
    rm -f artifacts.tar.gzip

- name: "Run backend server"
  become: yes
  shell: |
    cd /home/ubuntu/
    pm2 start dist/main.js
  register: launch

- name: "Check pm2 logs"
  shell: |
    pm2 log 0 --lines 50 --json --nostream
  register: logs

- name: Print launch results
  debug:
    msg: "{{ launch.stdout_lines }}"

- name: Print extraction results
  debug:
    msg: "{{ logs.stdout_lines }}"


