version: 2.1


jobs:
  create_infrastructure: # Job for lab01
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: create ec2 instance stack in cloudformation
          command: |
            aws cloudformation deploy --template-file project03/lab01/template.yml --stack-name websv01

  configure_infrastructure: # Job for lab02
    docker:
      - image: python:3.7-alpine3.11

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["5b:39:8b:9c:3b:d2:0b:fd:61:3b:4c:87:9b:e6:85:0e"]
      
      - run:
          name: Install dependencies
          command: 
            apk add --update ansible

      - run:
          name: Congure Server
          command: 
            ansible-playbook inventory.txt playbook.yml


          


workflows:
  Infrastructure_Workflow:
    jobs:
      - create_infrastructure
  