version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: create ec2 instance stack in cloudformation
          command: |
            aws cloudformation create-stack websv01 --region us-east-1 \
            --template-body file://labs/template.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"


workflows:
  Infrastructure_Workflow:
    jobs:
      - create_infrastructure
  