version: 2.1

jobs:
  create_infrastructure: # Job for lab01
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: create ec2 instance stack in cloudformation
          command: |
            aws cloudformation deploy --template-file project03/lab01/template.yml --stack-name websv01

  


# workflows:
#   Infrastructure_Workflow:
#     jobs:
#       - create_infrastructure
  