version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: create ec2 instance stack in cloudformation
          command: |
            aws cloudformation deploy --template-file labs/template.yml --stack-name websv01


workflows:
  Infrastructure_Workflow:
    jobs:
      - create_infrastructure
  